uv.lock needs to be read/write
For whatever reason, the uv.lock file needs to be writeable for the
bluecore-api container to start. Otherwise you will see this in your
logs:

```
error: failed to write to file `/bluecore_api/uv.lock`: Read-only file system (os error 30)
```